#!/usr/bin/env bash
# Install nginx web server 
sudo apt-get update && apt-get upgrade -y
sudo apt-get install nginx -y
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
