#!/usr/bin/env bash
# Install nginx web server 
sudo apt-get install nginx -y
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo echo "Holberton School" > /usr/share/nginx/html/index.html
