#!/usr/bin/env bash
# Configure the Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
sudo apt-get update -y
sudo apt-get install nginx -y
sudo chown -R ubuntu:ubuntu /var/www/
sudo chown -R ubuntu:ubuntu /etc/nginx
if [ -f /var/www/html/index.nginx-debian.html ]; then
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
fi
if [ -f /usr/share/nginx/html/index.html ]; then
sudo echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
fi
if [ -f /etc/nginx/sites-enabled/default ]; then
	sed -i -E 's/listen [0-9]+ default_server/listen 80 default_server/g' /etc/nginx/sites-enabled/default
	sed -i -E 's/listen \[::\]:[0-9]+ default_server/listen [::]:80 default_server/g' /etc/nginx/sites-enabled/default
fi	
if [ -f /etc/nginx/nginx.conf ]; then
	sed -i -E 's/listen [0-9]+ default_server/listen 80 default_server/g' /etc/nginx/nginx.conf
	sed -i -E 's/listen \[::\]:[0-9]+ default_server/listen [::]:80 default_server/g' /etc/nginx/nginx.conf
fi
sudo /etc/init.d/nginx start
# redirection start here
config_file=/etc/nginx/sites-enabled/default
sed -i -E "0,/listen \[::]:[0-9]+ .+;/s//& \n rewrite \^\/redirect_me\/\$ https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent\;/" "$config_file"
sudo /etc/init.d/nginx restart
# not found page 404
sed -i -E "0,/location (.)+\{/s//\n\terror_page 404 \/404.html\;\n\t&/" "$config_file"
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo /etc/init.d/nginx restart
