#!/usr/bin/env bash
#  configures a brand new Ubuntu machine to the requirements asked in
#this task
curl -s https://raw.githubusercontent.com/taiebchaabini/holberton-syst\
em_engineering-devops/master/0x0C-web_server/4-not_found_page_404 | sh
config_file=/etc/nginx/sites-enabled/default
sed -i -E "0,/listen \[::]:[0-9]+ .+;/s//& \n\tadd_header X-Served-By $(hostname) \;/" "$config_file"
service nginx restart
