#!/usr/bin/env bash
# Script for backing up a databases : MySQL dump must contain all MySQL 
# databases
if [[ $# -gt 0 ]]; then
current_date=$(date '+%d-%m-%y')
mysqldump -u root -p"$1"  --all-databases  > backup.sql > /dev/null 2>&1 && 
echo "backup.sql" && gzip -c backup.sql > "$current_date".tar.gz 
fi
