#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 ips
sed -i -E 's/listen [0-9]+ default_server/listen 80 default_server;/g' /etc/nginx/sites-enabled/default
sed -i -E 's/listen \[::\]:8080 default_server ipv6only=on/#listen \[::\]:8080
ipv6only=on/g' /etc/nginx/sites-enabled/default
