#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 ips
sed -i -E 's/8080/80/g' /etc/nginx/sites-enabled/default; sudo service nginx start; rm /var/run/nginx.pid
