#!/usr/bin/env bash
'
Bash script that:
Creates the file /var/run/holbertonscript.pid containing its PID
Displays To infinity and beyond indefinitely
Displays I hate the kill command when receiving a SIGTERM signal
Displays Y U no love me?! when receiving a SIGINT signal
Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
'
$pid;
$filename;
filename="/var/run/holbertonscript.pid"
touch $filename
echo "$$" > $filename 
pid=$$
msgterm()
{
    if [[ -e $filename ]]; then
        sudo rm /var/run/holbertonscript.pid
    fi
    echo "I hate the kill command"
    kill -9 $pid
}
msgint()
{
    echo "Y U no love me?!"
}
sigq()
{
    if [[ -e $filename ]]; then
    sudo rm /var/run/holbertonscript.pid
    fi
    kill -9 $pid
}
trap msgterm SIGTERM
trap msgint SIGINT
trap sigq SIGQUIT
while true; do
    echo "To infinity and beyond"
done
