#!/usr/bin/env bash
# Script that manages manage_my_process
$nbargs;
$filename;
$ppid;
$i;
i=0
nbargs=${#@}
if ((nbargs == 0)) || ((nbargs > 1)); then
    echo "Usage: manage_my_process {start|stop|restart}"
    exit;
fi
filename="/var/run/my_process.pid"
stopfn()
{
    if [[ -e $filename ]]; then
        ppid=$(cat $filename)
        kill "$ppid"
        rm /var/run/my_process.pid
    fi
    #i=$(pgrep bash -la | grep -c ./manage_my_process)
    #while ((i > 0)); do
    #    ppid=$(pgrep bash -la | grep ./manage_my_process | tail -n 1 | cut -f1 -d ' ')
    #    kill "$ppid"
    #    i=$(pgrep bash -la | grep -c ./manage_my_process)
    #done
}
startfn()
{
    nohup ./manage_my_process > /dev/null 2>1 &
    echo "$!" > $filename
}
case "$1" in
    stop)
        echo "manage_my_process stopped"
        stopfn
        ;;
    start)
        startfn
        echo "manage_my_process started"
    ;;
     restart)
         stopfn
         startfn
         echo "manage_my_process restarted"
    ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac
