#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely. 
message()
{
    echo "I am invincible!!!"
}
trap message  SIGTERM
while true; do
    echo "To infinity and beyond"
    sleep 2
done
