#!/usr/bin/env bash
# Bash script that displays the visitor IP along with the HTTP status code from the Apache log file. with awk
awk '{ printf "%s %s %s\n", $10, $1, $9 }' apache-access.log | sort -nrk1
