#!/usr/bin/env bash
# Bash script that displays the visitor IP along with the HTTP status code from the Apache log file. with awk with uniq occurance
filename='apache-access.log'
awk '{ printf "%s %s\n", $1, $9 }' $filename | uniq -c -f1 | sort -nr -k 1
