#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes. display hours from 0 to 12, display minutes from 1 to 59
i=0
b=0
while [ $i -lt 12 ]
    do
	b=0
	echo "Hour: $i"
	((i++))
	while [ $b -le 59 ]
	    do
	        echo "$b"
		((b++))
	    done 
    done
