#!/usr/bin/env bash
# Bash script that displays : The content of the current directory In a list format, Where only the part of the name after the first dash (-) is displayed, Do not display hidden files 
((i, mylist))
i=0
mylist=$(ls)
for i in $mylist
    do
	    echo "$i" | cut -f2 -d -
    done
