#!/usr/bin/env bash
# install the ufw firewall and setup a few rules on web-01.
sudo apt-get install ufw
sudo ufw reset
sudo ufw default deny incoming
sudo ufw allow 'OpenSSH'
sudo ufw allow 'Nginx Full'
sudo ufw enable
