#!/usr/bin/env bash
# nginx must be running as nginx user and listening on all active IPs on port 8080
sudo service nginx stop
sed -i -E 's/#user.+\;/user nginx;/' /etc/nginx/nginx.conf 
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
chown nginx:nginx /etc/nginx/ -R
chmod +rw /etc/nginx/nginx.conf
for pid in $(pidof apache2); do
    kill $pid
done
su -c 'service nginx start' nginx
