#!/usr/bin/env bash
# nginx must be running as nginx user and listening on all active IPs on port 8080
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
chown nginx:nginx /etc/nginx/ -R
chmod +rw /etc/nginx/nginx.conf
pkill apache2
su -c 'service nginx start' nginx
